apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-eb884f03d5454c89a93e004aac77ad26-depl
  labels:
    app: coll-eb884f03d5454c89a93e004aac77ad26
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-eb884f03d5454c89a93e004aac77ad26
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-eb884f03d5454c89a93e004aac77ad26
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-eb884f03d5454c89a93e004aac77ad26
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-eb884f03d5454c89a93e004aac77ad26
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping